[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  included_files = ["node_modules/@opentelemetry/instrumentation/hook.mjs", "node_modules/import-in-the-middle/hook.mjs"]